modLoader="javafml"
loaderVersion="[43,)"
license="Mozilla Public License 1.0 (MPL)"

[[mods]]
modId="copperio"
version="0.1.2"
displayName="CopperIO"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/copperio"
authors="hankb, MCreator"
description='''
Not Sponsored by Copper
'''

[[dependencies.copperio]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




